### ISSUE TITLE
Dataloader about BraTS2020

### ISSUE THREAD

**Issue by zzwFograinbow** [KidsWithTokens/MedSegDiff#156]
I noticed that the file form in the readme is inside the subfolder as t1.nii.gz, but in the default command run, the required file form is brats_train_001_XXX_123_w.nii.gz instead of XXX.nii.gz (XXX is the the name of the modality, e.g. t1, seg, etc.), and I'm sure I'm not the only one who hasn't read . /guided_diffusion/bratsloader.py  for the code, resulting in wasted time in naming processing and debugging the data. Hopefully the author will make changes to the readme.

**Comment by WuJunde** [comment]
updated, pls help to check if it is correct right know. thanks for your suggestion

**Comment by zzwFograinbow** [comment]
Yeah,It's correct I run a new to check it. Kind of you.
